// Generates assets/css/flame-sprites.css, the bonfire's pixel-art flame.
//
//   node scripts/pixel-flame.js
//
// Each stage has four frames drawn as ASCII art below (A B A C, so the tip
// wanders left and right without the flame ever jumping straight from one
// side to the other). Legend:  . empty   o outer   m mid   c core
// Every pixel becomes one box-shadow on a single square anchored at the
// bottom-centre of the sprite, one row below it so the anchor itself is never
// a visible pixel (outer shadows don't paint under their own box). Offsets
// are multiples of --p, the pixel size .fire-px sets; --o/--m/--c alias the
// theme's fire tokens there just to keep this file readable. (em offsets
// would be shorter but Chromium clamps font-size to a 6px minimum, which
// pulls the grid apart at hearth size.)

const FRAMES = {
  4: [
    [
      ".....o.....",
      ".....o.....",
      "....oo.....",
      "....ooo....",
      "...oooo....",
      "...ooooo...",
      "..oomooo...",
      "..oommoo...",
      ".ooommmoo..",
      ".oommmmoo..",
      ".oommcmmoo.",
      ".ommccmmmo.",
      ".ommcccmmo.",
      ".oommcmmoo.",
      "..oommmoo..",
      "...ooooo...",
    ],
    [
      "......o....",
      "......oo...",
      ".....oo....",
      "....ooo....",
      "....oooo...",
      "...oooooo..",
      "...oomooo..",
      "..ooommoo..",
      "..oommmmo..",
      ".ooommmmoo.",
      ".oommcmmoo.",
      ".ommcccmoo.",
      ".ommcccmmo.",
      ".oommcmmoo.",
      "..oommmoo..",
      "...ooooo...",
    ],
    [
      "...o.......",
      "...oo......",
      "....oo.....",
      "....ooo.o..",
      "...oooo.o..",
      "...ooooooo.",
      "..oommooo..",
      "..oommmoo..",
      ".ooommmmo..",
      ".oommmmmoo.",
      ".oommcmmoo.",
      ".ommcccmmo.",
      ".ommcccmmo.",
      ".oommcmmoo.",
      "..oommmoo..",
      "...ooooo...",
    ],
  ],
  3: [
    [
      "....o....",
      "....o....",
      "...oo....",
      "...ooo...",
      "..oooo...",
      "..oomoo..",
      ".oommmo..",
      ".oommmoo.",
      ".ommcmmo.",
      ".omcccmo.",
      ".ommcmmo.",
      "..ommmo..",
      "..ooooo..",
    ],
    [
      ".....o...",
      ".....o...",
      "....oo...",
      "...ooo...",
      "...oooo..",
      "..oomoo..",
      "..ommmoo.",
      ".oommmoo.",
      ".ommcmmo.",
      ".omcccmo.",
      ".ommcmmo.",
      "..ommmo..",
      "..ooooo..",
    ],
    [
      "...o.....",
      "...oo....",
      "...oo..o.",
      "..ooo..o.",
      "..ooooo..",
      "..oomoo..",
      ".oommmo..",
      ".oommmoo.",
      ".ommcmmo.",
      ".omcccmo.",
      ".ommcmmo.",
      "..ommmo..",
      "..ooooo..",
    ],
  ],
  2: [
    [
      "....o....",
      "....o....",
      "...oo....",
      "...ooo...",
      "...omo...",
      "..oommo..",
      "..ommmo..",
      ".oommmoo.",
      ".oomcmoo.",
      "..ooooo..",
    ],
    [
      ".....o...",
      "....oo...",
      "....oo...",
      "...ooo...",
      "...omo...",
      "..oommo..",
      "..ommmo..",
      ".oommmoo.",
      ".oomcmoo.",
      "..ooooo..",
    ],
    [
      "...o.....",
      "...oo....",
      "...oo.o..",
      "...ooo...",
      "...omo...",
      "..oommo..",
      "..ommmoo.",
      ".oommmoo.",
      ".oomcmoo.",
      "..ooooo..",
    ],
  ],
  1: [
    [
      "...o...",
      "...o...",
      "..oo...",
      "..omo..",
      ".oommo.",
      ".ommmo.",
      "..ooo..",
    ],
    [
      "....o..",
      "...oo..",
      "...oo..",
      "..omo..",
      ".oommo.",
      ".ommmo.",
      "..ooo..",
    ],
    [
      "..o....",
      "..oo...",
      "..oo...",
      "..omo..",
      ".ommoo.",
      ".ommmo.",
      "..ooo..",
    ],
  ],
};

const COLOR = { o: "var(--o)", m: "var(--m)", c: "var(--c)" };

function shadows(rows) {
  const h = rows.length;
  const w = rows[0].length;
  const mid = (w - 1) / 2;
  const out = [];
  rows.forEach((row, y) => {
    [...row].forEach((ch, x) => {
      if (ch === ".") return;
      const dx = x - mid;
      const dy = -(h - y); // bottom row lands one --px above the anchor
      out.push(`calc(${dx}*var(--p)) calc(${dy}*var(--p)) ${COLOR[ch]}`);
    });
  });
  return out.join(", ");
}

const fs = require("fs");
const path = require("path");

let css = "/* Generated by scripts/pixel-flame.js — edit the ASCII art there, not this. */\n";
for (const stage of [1, 2, 3, 4]) {
  const [a, b, c] = FRAMES[stage].map(shadows);
  css += `.bonfire[data-stage="${stage}"] .fire-px { box-shadow: ${a}; animation-name: px-flame-${stage}; }\n`;
  css += `@keyframes px-flame-${stage} {\n`;
  css += `  0%, 50%, 100% { box-shadow: ${a}; }\n`;
  css += `  25% { box-shadow: ${b}; }\n`;
  css += `  75% { box-shadow: ${c}; }\n`;
  css += `}\n`;
}
fs.writeFileSync(path.join(__dirname, "..", "assets", "css", "flame-sprites.css"), css);
